#cloud-config
---
manage_etc_hosts: true
fqdn: ${hostname}

package_update: true
package_upgrade: true

write_files:
- path: /etc/netplan/01-privnet.yaml
  content: |
    network:
      version: 2
      renderer: networkd
      ethernets:
        eth1:
          addresses:
            - ${ip_address}

runcmd:
- [ sh, -c, "sudo netplan apply" ]
